services:
  - type: web
    name: esp32-biometric-lock-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_USERNAME
        value: SRM_srm
      - key: ADMIN_PASSWORD
        value: srm@bio
      - key: JWT_SECRET
        generateValue: true
      - key: RATE_LIMIT_CHECK_PER_MINUTE
        value: "180"
      - key: RATE_LIMIT_LOG_PER_MINUTE
        value: "60"
